### ISSUE TITLE
Make user-visible routes RESTful 

### ISSUE THREAD

**Issue by vegetabill** [GrunuffyGit/ProPlan#1]
- `/ViewPlan/:planID` 
- `/MyPlans`

Try to think of more RESTful, resource-oriented routes for these cool custom page routes in the same way you changed the APIs

https://github.com/GrunuffyGit/ProPlan/blob/9f3a20dd916125a0c6b244288d6e4cbd710a8ab3/index.js#L18

**Comment by vegetabill** [comment]
e.g. `/plans/1` or `plans/mine`

**Comment by GrunuffyGit** [comment]
fixed client and server side routes
